services:
  db:
    image: postgis/postgis:16-3.4
    # Image PostGIS officielle basée sur PostgreSQL 16
    # Inclut toutes les extensions spatiales nécessaires
    container_name: postgres-renbancs
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: renbancs
    ports:
      - "5438:5432"
      # Port 5437 sur ta machine pour éviter les conflits
    volumes:
      - renbancs_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  renbancs_data:
